apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devopsrolebinding
  namespace: devops
subjects:
  - kind: User
    name: "Bob"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: devopsrole
  apiGroup: rbac.authorization.k8s.io