kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: devopsrolebinding
  namespace: devops
subjects:
  - kind: ServiceAccount
    name: bob
    namespace: devops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: devopsrole